import BuildHelper._

import zio.sbt.githubactions.Step

inThisBuild(
  List(
    organization := "dev.zio",
    homepage     := Some(url("https://zio.github.io/zio-cache/")),
    licenses     := List("Apache-2.0" -> url("http://www.apache.org/licenses/LICENSE-2.0")),
    developers := List(
      Developer(
        "jdegoes",
        "John De Goes",
        "john@degoes.net",
        url("http://degoes.net")
      )
    ),
    pgpPassphrase := sys.env.get("PGP_PASSWORD").map(_.toArray),
    pgpPublicRing := file("/tmp/public.asc"),
    pgpSecretRing := file("/tmp/secret.asc"),
    // zio-sbt-ci: this project predates zio-sbt-ecosystem, so kept off Scala/Java version
    // matrices supplied by that plugin (`lint`/`prepare` commands aren't available here either,
    // hence overriding the lint step below to reuse this build's own `check` alias).
    ciEnabledBranches    := Seq("master"),
    ciDefaultJavaVersion := "8",
    ciTargetJavaVersions := Seq("8", "11"),
    ciCheckWebsiteBuildProcess := Seq(
      Step.SingleStep(name = "Check Document Generation", run = Some("sbt docs/docusaurusCreateSite"))
    ),
    // No zio-sbt-website / docs/index.md setup in this repo: README isn't autogenerated, and there's
    // no npm-published docs site to notify downstream.
    ciUpdateReadmeJobs := Seq.empty,
    ciPostReleaseJobs  := Seq.empty
  )
)

// `lint` (from zio-sbt-ecosystem's Commands.scala) isn't on the classpath here; reuse this
// build's own `check` alias instead, keeping the drift-check step zio-sbt-ci prepends untouched.
ThisBuild / ciLintJobs := (ThisBuild / ciLintJobs).value.map { job =>
  job.copy(steps = job.steps.map {
    case s: Step.SingleStep if s.name == "Lint" => s.copy(run = Some("sbt --no-colors check"))
    case other                                  => other
  })
}

ThisBuild / ciTargetScalaVersions := targetScalaVersionsFor(zioCacheJVM, zioCacheJS, zioCacheNative).value

addCommandAlias("fmt", "all scalafmtSbt scalafmt test:scalafmt")
addCommandAlias("fix", "; all compile:scalafix test:scalafix; all scalafmtSbt scalafmtAll")
addCommandAlias("check", "; scalafmtSbtCheck; scalafmtCheckAll; compile:scalafix --check; test:scalafix --check")
addCommandAlias("benchmark", "benchmarks/Jmh/run")

addCommandAlias(
  "testJVM",
  ";zioCacheJVM/test"
)
addCommandAlias(
  "testJS",
  ";zioCacheJS/test"
)
addCommandAlias(
  "testNative",
  ";zioCacheNative/test:compile"
)

val zioVersion = "1.0.12"

lazy val root = project
  .in(file("."))
  .settings(
    publish / skip := true,
    unusedCompileDependenciesFilter -= moduleFilter("org.scala-js", "scalajs-library")
  )
  .aggregate(
    zioCacheJVM,
    zioCacheJS,
    zioCacheNative,
    benchmarks,
    docs
  )

lazy val zioCache = crossProject(JSPlatform, JVMPlatform, NativePlatform)
  .in(file("zio-cache"))
  .settings(stdSettings("zio-cache"))
  .settings(crossProjectSettings)
  .settings(buildInfoSettings("zio.cache"))
  .settings(
    libraryDependencies ++= Seq(
      "dev.zio"                %% "zio"                     % zioVersion,
      "org.scala-lang.modules" %% "scala-collection-compat" % "2.7.0",
      "dev.zio"                %% "zio-test"                % zioVersion % Test,
      "dev.zio"                %% "zio-test-sbt"            % zioVersion % Test
    )
  )
  .settings(testFrameworks += new TestFramework("zio.test.sbt.ZTestFramework"))
  .enablePlugins(BuildInfoPlugin)

lazy val zioCacheJS = zioCache.js
  .settings(jsSettings)
  .settings(libraryDependencies += "dev.zio" %%% "zio-test-sbt" % zioVersion % Test)
  .settings(scalaJSUseMainModuleInitializer := true)

lazy val zioCacheJVM = zioCache.jvm
  .settings(dottySettings)
  .settings(libraryDependencies += "dev.zio" %%% "zio-test-sbt" % zioVersion % Test)
  .settings(scalaReflectTestSettings)

lazy val zioCacheNative = zioCache.native
  .settings(nativeSettings)

lazy val benchmarks = project
  .in(file("zio-cache-benchmarks"))
  .settings(stdSettings("zio-cache"))
  .settings(
    publish / skip := true,
    moduleName     := "zio-cache-docs"
  )
  .dependsOn(zioCacheJVM)
  .enablePlugins(JmhPlugin)

lazy val docs = project
  .in(file("zio-cache-docs"))
  .settings(stdSettings("zio-cache"))
  .settings(
    publish / skip := true,
    moduleName     := "zio-cache-docs",
    scalacOptions -= "-Yno-imports",
    scalacOptions -= "-Xfatal-warnings",
    ScalaUnidoc / unidoc / unidocProjectFilter := inProjects(zioCacheJVM),
    ScalaUnidoc / unidoc / target              := (LocalRootProject / baseDirectory).value / "website" / "static" / "api",
    cleanFiles += (ScalaUnidoc / unidoc / target).value,
    docusaurusCreateSite     := docusaurusCreateSite.dependsOn(Compile / unidoc).value,
    docusaurusPublishGhpages := docusaurusPublishGhpages.dependsOn(Compile / unidoc).value
  )
  .dependsOn(zioCacheJVM)
  .enablePlugins(MdocPlugin, DocusaurusPlugin, ScalaUnidocPlugin)
